#!/bin/sh

MODE=$1
if [ -z "$MODE" ]; then
	echo "Error: specify MODE"
	exit 0
fi

CONFIGS=$XDG_CONFIG_HOME
if [ -z "$CONFIGS" ]; then
	CONFIGS="$HOME/.config"
fi

FILE="$CONFIGS/picom/picom.$MODE.conf"
if [ ! -f "$FILE" ]; then
	echo 'Error: no config FILE exists for specified MODE'
	exit 1
fi

rm "$CONFIGS/picom/picom.conf"
ln -s "$FILE" "$CONFIGS/picom/picom.conf"

exit 0
